# Change these first
owner: VYNX-Bot # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Bot
    url: https://Vynx.snaky4life.repl.co
  - name: Main Site
    url: https://thissitedoesnotexist.koj.co
  - name: Helpdesk
    url: https://thissitedoesnotexist.koj.co
  - name: Status Page
    url: https://VYNX-Bot.github.io/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VYNX Status
  introTitle: "Welcome to **VYNX's** status page."
  introMessage: Here you can see live stats on the uptime of the VYNX bot.
  navbar:
    - title: Home
      href: /
    - title: Support
      href: /
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

